### ISSUE TITLE
mplchart in NiceGUI framework

### ISSUE THREAD

**Issue by neodawn** [furechan/mplchart#7]
NiceGUI is a very good Python UI framework. NiceGUI supports matplotlib. Can you please share if mplchart can work with NiceGUI? If yes, can you please provide a small working example? Thanks.

**Related Links:**
https://nicegui.io/documentation/section_data_elements#pyplot_context
https://nicegui.io/documentation/section_data_elements#matplotlib

**Comment by furechan** [comment]
Hi @neodawn,

Thanks for mentioning nicegui. I had a quick look and also added a sample script `nicegui-mplchart.py` in the examples folder.

Hope this helps.

**Comment by neodawn** [comment]
You are awesome! Thanks for the example. I was able to run it in VSCode (Windows) using "Run current file in interactive window". 

But if I try to run it using just "Run current file" in VSCode, I get the following error captured below. Not sure if that is the expected behavior. I was able to run all the other NiceGUI examples using just "Run current file".

Traceback (most recent call last):
  File "c:\Tools\nice_gui_test\ng_mpl_01.py", line 31, in update_chart
    chart = Chart(title=ticker.value, max_bars=max_bars, figure=plot.fig)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\mplchart\chart.py", line 89, in __init__
    figure.clf()
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\figure.py", line 1027, in clf
    return self.clear(keep_observers=keep_observers)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\figure.py", line 3127, in clear
    super().clear(keep_observers=keep_observers)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\figure.py", line 996, in clear
    self.delaxes(ax)  # Remove ax from self._axstack.
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\figure.py", line 939, in delaxes
    self._remove_axes(ax, owners=[self._axstack, self._localaxes])
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\figure.py", line 956, in _remove_axes
    self._axobservers.process("_axes_change_event", self)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\cbook.py", line 303, in process
    self.exception_handler(exc)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\cbook.py", line 87, in _exception_printer
    raise exc
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\cbook.py", line 298, in process
    func(*args, **kwargs)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\figure.py", line 3232, in <lambda>
    self._axobservers.connect("_axes_change_event", lambda arg: func(arg))
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\backend_bases.py", line 2680, in notify_axes_change       
    self.toolbar.update()
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\backend_bases.py", line 3219, in update
    self.set_history_buttons()
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 897, in set_history_buttons
    self._buttons['Back']['state'] = state_map[can_back]
  File "C:\Users\neo\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1686, in __setitem__        
    self.configure({key: value})
  File "C:\Users\neo\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\neo\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Tools\nice_gui_test\ng_mpl_01.py", line 36, in <module>
    update_chart()
  File "c:\Tools\nice_gui_test\ng_mpl_01.py", line 30, in update_chart
    with plot:
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\nicegui\elements\pyplot.py", line 69, in __exit__
    plt.close(self.fig)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\pyplot.py", line 1098, in close
    _pylab_helpers.Gcf.destroy_fig(fig)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\_pylab_helpers.py", line 75, in destroy_fig
    cls.destroy(num)
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\_pylab_helpers.py", line 66, in destroy
    manager.destroy()
  File "C:\Tools\nice_gui_test\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 569, in destroy
    self._window_dpi.trace_remove('write', self._window_dpi_cbname)
  File "C:\Users\neo\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 455, in trace_remove
    self._tk.deletecommand(cbname)
_tkinter.TclError: can't delete Tcl command

**Comment by furechan** [comment]
Hi @neodawn,

I tried in VSCode on my Mac and had no such error. It may be specific to Windows or it may be related to the matplotlib configuration, but it's difficult to see what's happening here ...

**Comment by neodawn** [comment]
Ok. So I checked if there are any inputs in the NiceGUI GitHub issue page. Found a related issue.
https://github.com/zauberzeug/nicegui/issues/780

In the example you had shared, I added "close=False" and the issue was not observed anymore. Maybe you can update the example after validating.

```
with ui.pyplot(figsize=(9, 6), close=False) as plot:
    plt.plot()
```

Thanks again for the mplchart library and the example.

**Comment by furechan** [comment]
Great! I updated the example. Thanks

**Comment by neodawn** [comment]
I just checked the updated example; you have updated it as "close=True" instead of "close=False".

**Comment by furechan** [comment]
My mistake. Fixed
